spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.leak-detection-threshold=60000

server.port=8085

secret.key=vglsPsHvX5Q6yEzqDqBuvE4kdYF3QOdwKZ9SA8o6f7nyGfXZ7uFlZ0rfk6DwAsUw8bSkQ3nM0JVghC4zlJZ6Qg==

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.org.hibernate.envers.audit_strategy=org.hibernate.envers.strategy.ValidityAuditStrategy
spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=true

token.duration=24h
token.issuer=PriceMonitoring

spring.rabbitmq.publisher-confirm-type=none
spring.rabbitmq.template.reply-timeout=10s

scrapping.response.queue.name=scrapper-tasks-results

spring.rabbitmq.cache.channel.size=200
spring.rabbitmq.listener.simple.prefetch=20
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.concurrency=4

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.url=${SPRING_DATASOURCE_URL}


spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.virtual-host=vhost
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}



scrapping.server.address=${SCRAPPING_SERVER_ADDRESS}
scrapping.server.port=${SCRAPPING_SERVER_PORT}

management.endpoints.enabled-by-default=false
management.endpoint.prometheus.enabled=true
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=prometheus,health

spring.datasource.hikari.data-source-properties.applicationName=BackEnd

spring.liquibase.change-log=classpath*:liquibase/root-changelog.xml
spring.liquibase.contexts=data

logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=off

send.grid.from=dimitrijchannel@gmail.com

confirmation.token.duration=10m

#rate limiting
rate.limit.email.capacity=1
rate.limit.email.refillStrategy=INTERVAL
rate.limit.email.refillTokens=1
rate.limit.email.refillPeriod=1d

rate.limit.password.capacity=1
rate.limit.password.refillStrategy=INTERVAL
rate.limit.password.refillTokens=1
rate.limit.password.refillPeriod=1d

rate.limit.api.capacity=5
rate.limit.api.refillStrategy=GREEDY
rate.limit.api.refillTokens=5
rate.limit.api.refillPeriod=1s

#subscriptions
app.subscription.user.maxMonitorList=10
app.subscription.user.maxRooms=10

app.subscription.basic.maxMonitorList=20
app.subscription.basic.maxRooms=20

app.subscription.premium.maxMonitorList=50
